import type { AppShortcut } from '@/types/jarvis';

export interface CommonApp {
  id: string;
  name: string;
  path: string;
  aliases: string[];
  icon: string; // emoji for now
  launchCmd: string; // Windows shell command
}

export const commonApps: CommonApp[] = [
  {
    id: 'chrome',
    name: 'Google Chrome',
    path: 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',
    aliases: ['chrome', 'google chrome', 'browser'],
    icon: '🌐',
    launchCmd: 'start chrome',
  },
  {
    id: 'edge',
    name: 'Microsoft Edge',
    path: 'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe',
    aliases: ['edge', 'microsoft edge'],
    icon: '🌊',
    launchCmd: 'start msedge',
  },
  {
    id: 'firefox',
    name: 'Mozilla Firefox',
    path: 'C:\\Program Files\\Mozilla Firefox\\firefox.exe',
    aliases: ['firefox', 'mozilla'],
    icon: '🦊',
    launchCmd: 'start firefox',
  },
  {
    id: 'brave',
    name: 'Brave Browser',
    path: 'C:\\Program Files\\BraveSoftware\\Brave-Browser\\Application\\brave.exe',
    aliases: ['brave', 'brave browser'],
    icon: '🦁',
    launchCmd: 'start brave',
  },
  {
    id: 'spotify',
    name: 'Spotify',
    path: 'C:\\Users\\%USERNAME%\\AppData\\Roaming\\Spotify\\Spotify.exe',
    aliases: ['spotify', 'music'],
    icon: '🎵',
    launchCmd: 'start spotify:',
  },
  {
    id: 'discord',
    name: 'Discord',
    path: 'C:\\Users\\%USERNAME%\\AppData\\Local\\Discord\\app-*\\Discord.exe',
    aliases: ['discord'],
    icon: '💬',
    launchCmd: 'start discord:',
  },
  {
    id: 'telegram',
    name: 'Telegram',
    path: 'C:\\Users\\%USERNAME%\\AppData\\Roaming\\Telegram Desktop\\Telegram.exe',
    aliases: ['telegram'],
    icon: '✈️',
    launchCmd: 'start telegram:',
  },
  {
    id: 'whatsapp',
    name: 'WhatsApp',
    path: 'C:\\Program Files\\WindowsApps\\WhatsApp',
    aliases: ['whatsapp'],
    icon: '📱',
    launchCmd: 'start whatsapp:',
  },
  {
    id: 'slack',
    name: 'Slack',
    path: 'C:\\Users\\%USERNAME%\\AppData\\Local\\slack\\slack.exe',
    aliases: ['slack'],
    icon: '💼',
    launchCmd: 'start slack:',
  },
  {
    id: 'zoom',
    name: 'Zoom',
    path: 'C:\\Users\\%USERNAME%\\AppData\\Roaming\\Zoom\\bin\\Zoom.exe',
    aliases: ['zoom', 'zoom meeting'],
    icon: '📹',
    launchCmd: 'start zoommtg:',
  },
  {
    id: 'obs',
    name: 'OBS Studio',
    path: 'C:\\Program Files\\obs-studio\\bin\\64bit\\obs64.exe',
    aliases: ['obs', 'obs studio', 'streaming'],
    icon: '🎥',
    launchCmd: 'start "" "C:\\Program Files\\obs-studio\\bin\\64bit\\obs64.exe"',
  },
  {
    id: 'steam',
    name: 'Steam',
    path: 'C:\\Program Files (x86)\\Steam\\steam.exe',
    aliases: ['steam', 'games'],
    icon: '🎮',
    launchCmd: 'start steam:',
  },
  {
    id: 'epic',
    name: 'Epic Games',
    path: 'C:\\Program Files (x86)\\Epic Games\\Launcher\\Portal\\Binaries\\Win64\\EpicGamesLauncher.exe',
    aliases: ['epic', 'epic games', 'epic launcher'],
    icon: '🎮',
    launchCmd: 'start com.epicgames.launcher:',
  },
  {
    id: 'vscode',
    name: 'Visual Studio Code',
    path: 'C:\\Users\\%USERNAME%\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe',
    aliases: ['vscode', 'vs code', 'code'],
    icon: '💻',
    launchCmd: 'start code',
  },
  {
    id: 'vlc',
    name: 'VLC Media Player',
    path: 'C:\\Program Files\\VideoLAN\\VLC\\vlc.exe',
    aliases: ['vlc', 'media player', 'video player'],
    icon: '🎬',
    launchCmd: 'start vlc',
  },
  {
    id: 'notion',
    name: 'Notion',
    path: 'C:\\Users\\%USERNAME%\\AppData\\Local\\Programs\\Notion\\Notion.exe',
    aliases: ['notion', 'notes'],
    icon: '📓',
    launchCmd: 'start notion:',
  },
  {
    id: 'youtube',
    name: 'YouTube',
    path: 'https://youtube.com',
    aliases: ['youtube', 'yt'],
    icon: '▶️',
    launchCmd: 'start https://youtube.com',
  },
  {
    id: 'netflix',
    name: 'Netflix',
    path: 'https://netflix.com',
    aliases: ['netflix'],
    icon: '🎬',
    launchCmd: 'start https://netflix.com',
  },
  {
    id: 'twitch',
    name: 'Twitch',
    path: 'https://twitch.tv',
    aliases: ['twitch'],
    icon: '📺',
    launchCmd: 'start https://twitch.tv',
  },
  {
    id: 'explorer',
    name: 'File Explorer',
    path: 'C:\\Windows\\explorer.exe',
    aliases: ['explorer', 'file explorer', 'files'],
    icon: '📁',
    launchCmd: 'start explorer',
  },
  {
    id: 'notepad',
    name: 'Notepad',
    path: 'C:\\Windows\\System32\\notepad.exe',
    aliases: ['notepad'],
    icon: '📝',
    launchCmd: 'start notepad',
  },
  {
    id: 'task-manager',
    name: 'Task Manager',
    path: 'C:\\Windows\\System32\\Taskmgr.exe',
    aliases: ['task manager', 'taskmgr'],
    icon: '📊',
    launchCmd: 'start taskmgr',
  },
  {
    id: 'terminal',
    name: 'Windows Terminal',
    path: 'C:\\Program Files\\WindowsApps\\Microsoft.WindowsTerminal',
    aliases: ['terminal', 'cmd', 'command prompt', 'powershell'],
    icon: '⬛',
    launchCmd: 'start wt',
  },
  {
    id: 'calculator',
    name: 'Calculator',
    path: 'C:\\Windows\\System32\\calc.exe',
    aliases: ['calculator', 'calc'],
    icon: '🧮',
    launchCmd: 'start calc',
  },
];

export function toAppShortcut(app: CommonApp): AppShortcut {
  return {
    id: app.id,
    name: app.name,
    path: app.path,
    aliases: app.aliases,
    icon: app.icon,
  };
}
